name: PROS Build Template

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run LemLib/pros-build
        id: test
<<<<<<< HEAD
        uses: LemLib/pros-build@v4.0.1
=======
        uses: LemLib/pros-build@v5.1.0
>>>>>>> master

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.test.outputs.name }}
<<<<<<< HEAD
          path: ${{ github.workspace }}/template/*
=======
          path: ${{ github.workspace }}/template/*
>>>>>>> master
